use std::path::Path;

use lintai_api::ArtifactKind;

use super::FileTypeDetector;

#[test]
fn detects_v0_1_file_types() {
    let detector = FileTypeDetector::default();

    assert_eq!(
        detector
            .detect(Path::new("/tmp/SKILL.md"), "SKILL.md")
            .unwrap()
            .kind,
        ArtifactKind::Skill
    );
    assert_eq!(
        detector
            .detect(Path::new("/tmp/AGENTS.md"), "AGENTS.md")
            .unwrap()
            .kind,
        ArtifactKind::Instructions
    );
    assert_eq!(
        detector
            .detect(
                Path::new("/tmp/project/.github/copilot-instructions.md"),
                ".github/copilot-instructions.md"
            )
            .unwrap()
            .kind,
        ArtifactKind::Instructions
    );
    assert_eq!(
        detector
            .detect(
                Path::new("/tmp/project/docs/review.instructions.md"),
                "docs/review.instructions.md"
            )
            .unwrap()
            .kind,
        ArtifactKind::Instructions
    );
    assert_eq!(
        detector
            .detect(
                Path::new("/tmp/project/.github/instructions/review.md"),
                ".github/instructions/review.md"
            )
            .unwrap()
            .kind,
        ArtifactKind::Instructions
    );
    assert_eq!(
        detector
            .detect(
                Path::new("/tmp/project/docs/security.agent.md"),
                "docs/security.agent.md"
            )
            .unwrap()
            .kind,
        ArtifactKind::Instructions
    );
    assert_eq!(
        detector
            .detect(
                Path::new("/tmp/.cursor/rules/demo.mdc"),
                ".cursor/rules/demo.mdc"
            )
            .unwrap()
            .kind,
        ArtifactKind::CursorRules
    );
    assert_eq!(
        detector
            .detect(
                Path::new("/tmp/project/.cursor-plugin/plugin.json"),
                ".cursor-plugin/plugin.json"
            )
            .unwrap()
            .kind,
        ArtifactKind::CursorPluginManifest
    );
    assert_eq!(
        detector
            .detect(
                Path::new("/tmp/project/.cursor-plugin/hooks.json"),
                ".cursor-plugin/hooks.json"
            )
            .unwrap()
            .kind,
        ArtifactKind::CursorPluginHooks
    );
    assert_eq!(
        detector
            .detect(Path::new("/tmp/project/.mcp.json"), ".mcp.json")
            .unwrap()
            .kind,
        ArtifactKind::McpConfig
    );
    assert_eq!(
        detector
            .detect(
                Path::new("/tmp/project/.cursor/mcp.json"),
                ".cursor/mcp.json"
            )
            .unwrap()
            .kind,
        ArtifactKind::McpConfig
    );
    assert_eq!(
        detector
            .detect(
                Path::new("/tmp/project/.vscode/mcp.json"),
                ".vscode/mcp.json"
            )
            .unwrap()
            .kind,
        ArtifactKind::McpConfig
    );
    assert_eq!(
        detector
            .detect(Path::new("/tmp/project/.roo/mcp.json"), ".roo/mcp.json")
            .unwrap()
            .kind,
        ArtifactKind::McpConfig
    );
    assert_eq!(
        detector
            .detect(
                Path::new("/tmp/project/.kiro/settings/mcp.json"),
                ".kiro/settings/mcp.json"
            )
            .unwrap()
            .kind,
        ArtifactKind::McpConfig
    );
    assert_eq!(
        detector
            .detect(Path::new("/tmp/project/server.json"), "server.json")
            .unwrap()
            .kind,
        ArtifactKind::ServerRegistryConfig
    );
    assert_eq!(
        detector
            .detect(
                Path::new("/tmp/project/.claude/settings.json"),
                ".claude/settings.json"
            )
            .unwrap()
            .kind,
        ArtifactKind::ClaudeSettings
    );
    assert_eq!(
        detector
            .detect(
                Path::new("/tmp/project/claude/settings.json"),
                "claude/settings.json"
            )
            .unwrap()
            .kind,
        ArtifactKind::ClaudeSettings
    );
    assert_eq!(
        detector
            .detect(
                Path::new("/tmp/project/.claude/mcp/chrome-devtools.json"),
                ".claude/mcp/chrome-devtools.json"
            )
            .unwrap()
            .kind,
        ArtifactKind::McpConfig
    );
    assert_eq!(
        detector
            .detect(
                Path::new("/tmp/project/pkg/mcp/testdata/toolsets-full-tools.json"),
                "pkg/mcp/testdata/toolsets-full-tools.json"
            )
            .unwrap()
            .kind,
        ArtifactKind::ToolDescriptorJson
    );
    assert_eq!(
        detector
            .detect(
                Path::new("/tmp/project/.github/workflows/ci.yml"),
                ".github/workflows/ci.yml"
            )
            .unwrap()
            .kind,
        ArtifactKind::GitHubWorkflow
    );
    assert_eq!(
        detector
            .detect(
                Path::new("/tmp/project/.cursor-plugin/commands/setup.md"),
                ".cursor-plugin/commands/setup.md"
            )
            .unwrap()
            .kind,
        ArtifactKind::CursorPluginCommand
    );
    assert_eq!(
        detector
            .detect(
                Path::new("/tmp/project/.cursor-plugin/agents/reviewer.md"),
                ".cursor-plugin/agents/reviewer.md"
            )
            .unwrap()
            .kind,
        ArtifactKind::CursorPluginAgent
    );
    assert!(
        detector
            .detect(Path::new("/tmp/project/tsconfig.json"), "tsconfig.json")
            .is_none()
    );
    assert!(
        detector
            .detect(Path::new("/tmp/project/docs/review.md"), "docs/review.md")
            .is_none()
    );
}
