use lintai_api::{ArtifactKind, SourceFormat};

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DetectionRuleSpec {
    pub priority: u8,
    pub file_name: Option<&'static str>,
    pub file_name_fragment: Option<&'static str>,
    pub suffix: Option<&'static str>,
    pub parent_dir: Option<&'static str>,
    pub path_fragment: Option<&'static str>,
    pub artifact_kind: ArtifactKind,
    pub format: SourceFormat,
}

pub fn detection_rules() -> Vec<DetectionRuleSpec> {
    let mut rules = vec![
        DetectionRuleSpec {
            priority: 0,
            file_name: Some("SKILL.md"),
            file_name_fragment: None,
            suffix: None,
            parent_dir: None,
            path_fragment: None,
            artifact_kind: ArtifactKind::Skill,
            format: SourceFormat::Markdown,
        },
        DetectionRuleSpec {
            priority: 0,
            file_name: Some("CLAUDE.md"),
            file_name_fragment: None,
            suffix: None,
            parent_dir: None,
            path_fragment: None,
            artifact_kind: ArtifactKind::Instructions,
            format: SourceFormat::Markdown,
        },
        DetectionRuleSpec {
            priority: 1,
            file_name: Some("mcp.json"),
            file_name_fragment: None,
            suffix: None,
            parent_dir: None,
            path_fragment: None,
            artifact_kind: ArtifactKind::McpConfig,
            format: SourceFormat::Json,
        },
        DetectionRuleSpec {
            priority: 1,
            file_name: Some(".mcp.json"),
            file_name_fragment: None,
            suffix: None,
            parent_dir: None,
            path_fragment: None,
            artifact_kind: ArtifactKind::McpConfig,
            format: SourceFormat::Json,
        },
        DetectionRuleSpec {
            priority: 1,
            file_name: None,
            file_name_fragment: None,
            suffix: Some(".json"),
            parent_dir: None,
            path_fragment: Some(".claude/mcp/"),
            artifact_kind: ArtifactKind::McpConfig,
            format: SourceFormat::Json,
        },
        DetectionRuleSpec {
            priority: 1,
            file_name: Some("plugin.json"),
            file_name_fragment: None,
            suffix: None,
            parent_dir: None,
            path_fragment: Some(".cursor-plugin/"),
            artifact_kind: ArtifactKind::CursorPluginManifest,
            format: SourceFormat::Json,
        },
        DetectionRuleSpec {
            priority: 1,
            file_name: Some("hooks.json"),
            file_name_fragment: None,
            suffix: None,
            parent_dir: None,
            path_fragment: Some(".cursor-plugin/"),
            artifact_kind: ArtifactKind::CursorPluginHooks,
            format: SourceFormat::Json,
        },
        DetectionRuleSpec {
            priority: 2,
            file_name: Some("tools.json"),
            file_name_fragment: None,
            suffix: None,
            parent_dir: None,
            path_fragment: None,
            artifact_kind: ArtifactKind::ToolDescriptorJson,
            format: SourceFormat::Json,
        },
        DetectionRuleSpec {
            priority: 2,
            file_name: None,
            file_name_fragment: Some("tools"),
            suffix: Some(".json"),
            parent_dir: None,
            path_fragment: None,
            artifact_kind: ArtifactKind::ToolDescriptorJson,
            format: SourceFormat::Json,
        },
        DetectionRuleSpec {
            priority: 2,
            file_name: None,
            file_name_fragment: None,
            suffix: Some(".tool.json"),
            parent_dir: None,
            path_fragment: None,
            artifact_kind: ArtifactKind::ToolDescriptorJson,
            format: SourceFormat::Json,
        },
        DetectionRuleSpec {
            priority: 2,
            file_name: None,
            file_name_fragment: None,
            suffix: Some(".tools.json"),
            parent_dir: None,
            path_fragment: None,
            artifact_kind: ArtifactKind::ToolDescriptorJson,
            format: SourceFormat::Json,
        },
        DetectionRuleSpec {
            priority: 3,
            file_name: None,
            file_name_fragment: None,
            suffix: Some(".mdc"),
            parent_dir: None,
            path_fragment: None,
            artifact_kind: ArtifactKind::CursorRules,
            format: SourceFormat::Markdown,
        },
        DetectionRuleSpec {
            priority: 3,
            file_name: Some(".cursorrules"),
            file_name_fragment: None,
            suffix: None,
            parent_dir: None,
            path_fragment: None,
            artifact_kind: ArtifactKind::CursorRules,
            format: SourceFormat::Markdown,
        },
        DetectionRuleSpec {
            priority: 4,
            file_name: None,
            file_name_fragment: None,
            suffix: Some(".sh"),
            parent_dir: Some("hooks"),
            path_fragment: Some(".cursor-plugin/hooks/"),
            artifact_kind: ArtifactKind::CursorHookScript,
            format: SourceFormat::Shell,
        },
        DetectionRuleSpec {
            priority: 4,
            file_name: None,
            file_name_fragment: None,
            suffix: Some(".md"),
            parent_dir: Some("commands"),
            path_fragment: Some(".cursor-plugin/commands/"),
            artifact_kind: ArtifactKind::CursorPluginCommand,
            format: SourceFormat::Markdown,
        },
        DetectionRuleSpec {
            priority: 4,
            file_name: None,
            file_name_fragment: None,
            suffix: Some(".md"),
            parent_dir: Some("agents"),
            path_fragment: Some(".cursor-plugin/agents/"),
            artifact_kind: ArtifactKind::CursorPluginAgent,
            format: SourceFormat::Markdown,
        },
    ];
    rules.sort_by_key(|rule| rule.priority);
    rules
}
