use lintai_testing::{assert_case_summary, discover_case_dirs};

use super::{case_dir, corpus_root, harness, load_case};

#[test]
fn benign_corpus_case_dirs_are_discoverable() {
    let cases = discover_case_dirs(&corpus_root("benign")).unwrap();
    let names = cases
        .iter()
        .map(|path| {
            path.file_name()
                .and_then(|value| value.to_str())
                .unwrap()
                .to_owned()
        })
        .collect::<Vec<_>>();

    assert_eq!(
        names,
        vec![
            "agents-autonomy-without-bypass-safe",
            "agents-untrusted-input-warning-safe",
            "claude-never-header-approval-safe",
            "claude-settings-bash-specific-safe",
            "claude-settings-bypass-fixture-safe",
            "claude-settings-bypass-safe",
            "claude-settings-curl-fixture-safe",
            "claude-settings-curl-specific-safe",
            "claude-settings-dangerous-http-hook-fixture-safe",
            "claude-settings-dangerous-http-hook-safe",
            "claude-settings-destructive-git-specific-safe",
            "claude-settings-edit-specific-safe",
            "claude-settings-edit-wildcard-fixture-safe",
            "claude-settings-empty-enabled-mcpjson-servers-safe",
            "claude-settings-gh-api-delete-permission-specific-safe",
            "claude-settings-gh-api-patch-permission-specific-safe",
            "claude-settings-gh-api-put-permission-specific-safe",
            "claude-settings-gh-mutation-specific-safe",
            "claude-settings-gh-pr-fixture-safe",
            "claude-settings-gh-pr-specific-safe",
            "claude-settings-gh-repo-edit-release-create-specific-safe",
            "claude-settings-gh-repo-release-delete-specific-safe",
            "claude-settings-gh-repo-transfer-release-upload-specific-safe",
            "claude-settings-gh-secret-variable-workflow-specific-safe",
            "claude-settings-git-add-fixture-safe",
            "claude-settings-git-add-specific-safe",
            "claude-settings-git-branch-fixture-safe",
            "claude-settings-git-branch-specific-safe",
            "claude-settings-git-checkout-fixture-safe",
            "claude-settings-git-checkout-specific-safe",
            "claude-settings-git-clone-fixture-safe",
            "claude-settings-git-clone-specific-safe",
            "claude-settings-git-commit-fixture-safe",
            "claude-settings-git-commit-specific-safe",
            "claude-settings-git-config-fixture-safe",
            "claude-settings-git-config-specific-safe",
            "claude-settings-git-fetch-fixture-safe",
            "claude-settings-git-fetch-specific-safe",
            "claude-settings-git-ls-remote-fixture-safe",
            "claude-settings-git-ls-remote-specific-safe",
            "claude-settings-git-push-fixture-safe",
            "claude-settings-git-push-specific-safe",
            "claude-settings-git-stash-fixture-safe",
            "claude-settings-git-stash-specific-safe",
            "claude-settings-git-tag-fixture-safe",
            "claude-settings-git-tag-specific-safe",
            "claude-settings-glob-specific-safe",
            "claude-settings-glob-wildcard-fixture-safe",
            "claude-settings-grep-specific-safe",
            "claude-settings-grep-wildcard-fixture-safe",
            "claude-settings-home-directory-fixture-safe",
            "claude-settings-home-directory-redirect-safe",
            "claude-settings-home-directory-safe-project-scoped",
            "claude-settings-hook-timeout-fixture-safe",
            "claude-settings-hook-timeout-safe",
            "claude-settings-http-hook-fixture-safe",
            "claude-settings-http-hook-loopback-safe",
            "claude-settings-http-hook-safe",
            "claude-settings-matcher-fixture-safe",
            "claude-settings-matcher-pretooluse-safe",
            "claude-settings-missing-required-matcher-fixture-safe",
            "claude-settings-network-command-safe",
            "claude-settings-network-tls-verified-safe",
            "claude-settings-npm-exec-bunx-specific-safe",
            "claude-settings-npx-specific-safe",
            "claude-settings-package-command-safe",
            "claude-settings-package-runner-specific-safe",
            "claude-settings-pinned-launcher-safe",
            "claude-settings-pip-command-safe",
            "claude-settings-read-specific-safe",
            "claude-settings-read-wildcard-fixture-safe",
            "claude-settings-repo-external-absolute-hook-fixture-safe",
            "claude-settings-repo-external-absolute-hook-safe",
            "claude-settings-required-matcher-present-safe",
            "claude-settings-schema-fixture-safe",
            "claude-settings-schema-present-safe",
            "claude-settings-scope-search-specific-safe",
            "claude-settings-unsafe-path-fixture-safe",
            "claude-settings-unsafe-path-specific-safe",
            "claude-settings-unscoped-tool-family-specific-safe",
            "claude-settings-unscoped-websearch-fixture-safe",
            "claude-settings-webfetch-raw-github-fixture-safe",
            "claude-settings-webfetch-specific-safe",
            "claude-settings-webfetch-wildcard-fixture-safe",
            "claude-settings-websearch-scoped-safe",
            "claude-settings-websearch-specific-safe",
            "claude-settings-websearch-wildcard-fixture-safe",
            "claude-settings-wget-fixture-safe",
            "claude-settings-wget-specific-safe",
            "claude-settings-write-specific-safe",
            "claude-settings-write-wildcard-fixture-safe",
            "claude-transcript-bare-pip-no-uv-preference-safe",
            "claude-transcript-uv-pip-safe",
            "claude-unpinned-pip-git-install-commit-pinned-safe",
            "copilot-instructions-too-long-fixture-safe",
            "copilot-instructions-within-limit-safe",
            "copilot-path-specific-correct-suffix-safe",
            "copilot-path-specific-fixture-safe",
            "copilot-path-specific-invalid-applyto-fixture-safe",
            "copilot-path-specific-invalid-applyto-glob-fixture-safe",
            "copilot-path-specific-valid-applyto-safe",
            "copilot-path-specific-with-applyto-safe",
            "copilot-path-specific-wrong-suffix-fixture-safe",
            "copilot-untrusted-input-generic-safe",
            "cursor-plugin-clean-basic",
            "cursor-plugin-safe-paths",
            "cursor-plugin-tls-verified-basic",
            "cursor-rule-alwaysapply-boolean-safe",
            "cursor-rule-alwaysapply-fixture-safe",
            "cursor-rule-alwaysapply-no-globs-safe",
            "cursor-rule-alwaysapply-redundant-globs-fixture-safe",
            "cursor-rule-globs-fixture-safe",
            "cursor-rule-globs-sequence-safe",
            "cursor-rule-missing-description-fixture-safe",
            "cursor-rule-missing-description-safe",
            "cursor-rule-unknown-frontmatter-fixture-safe",
            "cursor-rule-unknown-frontmatter-supported-keys-safe",
            "docker-compose-digest-pinned-image",
            "docker-compose-safe-runtime",
            "docker-compose-tagged-image-safe",
            "dockerfile-digest-pinned-base-image",
            "dockerfile-final-stage-nonroot-user",
            "dockerfile-safe-run",
            "dockerfile-tagged-base-image-safe",
            "gemini-mcp-docker-digest-pinned-safe",
            "github-workflow-env-indirected-safe",
            "github-workflow-pinned-third-party-action",
            "github-workflow-pull-request-target-safe-checkout",
            "github-workflow-read-only-permissions",
            "github-workflow-third-party-action-read-only-safe",
            "hook-auth-dynamic-safe",
            "hook-base64-decode-safe",
            "mcp-args-non-sudo-safe",
            "mcp-authorization-placeholder-safe",
            "mcp-autoapprove-bash-specific-safe",
            "mcp-autoapprove-curl-wget-specific-safe",
            "mcp-autoapprove-gh-api-mutation-family-specific-safe",
            "mcp-autoapprove-gh-delete-family-specific-safe",
            "mcp-autoapprove-gh-mutation-family-specific-safe",
            "mcp-autoapprove-gh-release-transfer-family-specific-safe",
            "mcp-autoapprove-git-destructive-family-specific-safe",
            "mcp-autoapprove-git-history-family-specific-safe",
            "mcp-autoapprove-git-push-gh-api-post-specific-safe",
            "mcp-autoapprove-mutable-runner-family-specific-safe",
            "mcp-autoapprove-package-install-family-specific-safe",
            "mcp-autoapprove-persistence-family-specific-safe",
            "mcp-autoapprove-privileged-shell-family-specific-safe",
            "mcp-autoapprove-repo-fetch-family-specific-safe",
            "mcp-autoapprove-repo-management-family-specific-safe",
            "mcp-autoapprove-specific-safe",
            "mcp-autoapprove-sudo-rm-specific-safe",
            "mcp-autoapprove-tools-false-safe",
            "mcp-autoapprove-unsafe-path-family-specific-safe",
            "mcp-autoapprove-unscoped-tool-family-specific-safe",
            "mcp-autoapprove-webfetch-raw-github-safe",
            "mcp-autoapprove-wildcard-tool-family-specific-safe",
            "mcp-capabilities-scoped-safe",
            "mcp-command-non-sudo-safe",
            "mcp-description-safe",
            "mcp-docker-digest-pinned-safe",
            "mcp-docker-named-volume-safe",
            "mcp-docker-safe-run",
            "mcp-network-command-safe",
            "mcp-network-tls-verified-command-safe",
            "mcp-nonsensitive-env-reference-safe",
            "mcp-pinned-launcher-safe",
            "mcp-public-endpoint-safe",
            "mcp-safe-basic",
            "mcp-safe-client-envfile-config",
            "mcp-sandbox-enabled-safe",
            "mcp-secret-placeholder-safe",
            "mcp-shell-wrapper-args-safe",
            "mcp-trust-tools-false-safe",
            "mcp-trust-verified-basic",
            "mcp-trusted-endpoint-safe",
            "mcp-vscode-placeholder-envfile-safe",
            "mixed-clean-workspace",
            "package-manifest-pinned-dependency-safe",
            "package-manifest-registry-archive-safe",
            "package-manifest-registry-dependency-safe",
            "package-manifest-safe-lifecycle-script",
            "plugin-agent-hooks-fixture-safe",
            "plugin-agent-markdown-covered",
            "plugin-agent-mcpservers-fixture-safe",
            "plugin-agent-permission-mode-fixture-safe",
            "plugin-agent-without-permission-mode-safe",
            "plugin-hook-command-safe",
            "policy-truthful-basic",
            "server-json-auth-header-placeholder-safe",
            "server-json-header-variable-defined",
            "server-json-loopback-package-transport-safe",
            "server-json-remote-variable-defined",
            "skill-base64-fenced-safe",
            "skill-bash-wildcard-allowed-tools-specific-safe",
            "skill-cargo-https-git-install-safe",
            "skill-cargo-https-index-safe",
            "skill-chgrp-allowed-tools-specific-safe",
            "skill-chmod-allowed-tools-specific-safe",
            "skill-chown-allowed-tools-specific-safe",
            "skill-clean-basic",
            "skill-command-snippet-bare-npx-safe",
            "skill-command-snippet-without-mcp-context-safe",
            "skill-core-wildcard-allowed-tools-specific-safe",
            "skill-curl-allowed-tools-fixture-safe",
            "skill-curl-allowed-tools-specific-safe",
            "skill-docker-digest-pinned-safe",
            "skill-docker-host-escape-safe-ordinary-run",
            "skill-docker-local-image-safe",
            "skill-edit-unsafe-path-allowed-tools-specific-safe",
            "skill-explicit-approval-required-safe",
            "skill-fenced-pipe-shell-safe",
            "skill-generic-npx-safe",
            "skill-gh-api-delete-allowed-tools-specific-safe",
            "skill-gh-api-patch-allowed-tools-specific-safe",
            "skill-gh-api-put-allowed-tools-specific-safe",
            "skill-gh-mutation-specific-safe",
            "skill-gh-pr-allowed-tools-fixture-safe",
            "skill-gh-pr-allowed-tools-specific-safe",
            "skill-gh-repo-edit-release-create-specific-safe",
            "skill-gh-repo-release-delete-specific-safe",
            "skill-gh-repo-transfer-release-upload-specific-safe",
            "skill-gh-secret-variable-workflow-specific-safe",
            "skill-git-add-allowed-tools-specific-safe",
            "skill-git-am-allowed-tools-specific-safe",
            "skill-git-apply-allowed-tools-specific-safe",
            "skill-git-branch-allowed-tools-specific-safe",
            "skill-git-cherry-pick-allowed-tools-specific-safe",
            "skill-git-clean-allowed-tools-specific-safe",
            "skill-git-clone-allowed-tools-fixture-safe",
            "skill-git-clone-allowed-tools-specific-safe",
            "skill-git-config-allowed-tools-specific-safe",
            "skill-git-fetch-allowed-tools-specific-safe",
            "skill-git-https-clone-safe",
            "skill-git-https-remote-safe",
            "skill-git-inline-sslverify-true-safe",
            "skill-git-merge-allowed-tools-specific-safe",
            "skill-git-rebase-allowed-tools-specific-safe",
            "skill-git-reset-allowed-tools-specific-safe",
            "skill-git-restore-allowed-tools-specific-safe",
            "skill-git-ssl-no-verify-disabled-safe",
            "skill-git-sslverify-true-safe",
            "skill-git-tag-allowed-tools-specific-safe",
            "skill-glob-unsafe-path-allowed-tools-specific-safe",
            "skill-html-comment-safe",
            "skill-js-package-config-https-registry-safe",
            "skill-js-package-strict-ssl-true-safe",
            "skill-markdown-network-tls-bypass-powershell-warning-safe",
            "skill-markdown-network-tls-bypass-warning-safe",
            "skill-metadata-service-deny-list-safe",
            "skill-mutable-mcp-launcher-safety-guidance-safe",
            "skill-npm-exec-bunx-specific-safe",
            "skill-npm-https-registry-safe",
            "skill-npm-https-source-safe",
            "skill-npx-git-ls-remote-specific-safe",
            "skill-package-command-allowed-tools-safe",
            "skill-pip-config-https-find-links-safe",
            "skill-pip-config-https-index-safe",
            "skill-pip-config-unrelated-key-safe",
            "skill-pip-https-find-links-safe",
            "skill-pip-https-git-install-safe",
            "skill-pip-https-index-safe",
            "skill-pip-https-source-safe",
            "skill-pip-index-url-safe",
            "skill-project-scoped-path-safe",
            "skill-public-key-pem-safe",
            "skill-read-unsafe-path-allowed-tools-specific-safe",
            "skill-reviewed-frontmatter-tool-grants-safe",
            "skill-rm-allowed-tools-specific-safe",
            "skill-scoped-bash-allowed-tools-safe",
            "skill-scoped-webfetch-allowed-tools-safe",
            "skill-su-allowed-tools-specific-safe",
            "skill-sudo-allowed-tools-specific-safe",
            "skill-unscoped-bash-fixture-safe",
            "skill-unscoped-edit-allowed-tools-fixture-safe",
            "skill-unscoped-edit-allowed-tools-specific-safe",
            "skill-unscoped-glob-allowed-tools-fixture-safe",
            "skill-unscoped-glob-allowed-tools-specific-safe",
            "skill-unscoped-grep-allowed-tools-fixture-safe",
            "skill-unscoped-grep-allowed-tools-specific-safe",
            "skill-unscoped-read-allowed-tools-fixture-safe",
            "skill-unscoped-read-allowed-tools-specific-safe",
            "skill-unscoped-write-allowed-tools-fixture-safe",
            "skill-unscoped-write-allowed-tools-specific-safe",
            "skill-untrusted-input-negated-safe",
            "skill-uvx-dlx-pipx-specific-safe",
            "skill-webfetch-raw-github-allowed-tools-specific-safe",
            "skill-wget-allowed-tools-fixture-safe",
            "skill-wget-allowed-tools-specific-safe",
            "skill-wildcard-tools-explicit-allowlist-safe",
            "skill-wildcard-tools-fixture-safe",
            "skill-write-unsafe-path-allowed-tools-specific-safe",
            "tool-json-anthropic-strict-locked",
            "tool-json-mcp-valid-tool",
            "tool-json-openai-strict-locked",
            "tool-json-openai-strict-required-complete",
            "tool-json-unique-tool-names",
        ]
    );
}

#[test]
fn benign_corpus_cases_scan_cleanly() {
    let harness = harness();

    for case_dir in discover_case_dirs(&corpus_root("benign")).unwrap() {
        let manifest = load_case(&case_dir);
        let summary = harness
            .scan_case(&case_dir)
            .unwrap_or_else(|error| panic!("case {} failed to scan: {error}", manifest.id));
        assert_case_summary(&manifest, &summary);
    }
}

#[test]
fn mixed_clean_workspace_stays_clean() {
    let case_dir = case_dir("benign", "mixed-clean-workspace");
    let manifest = load_case(&case_dir);
    let summary = harness().scan_case(&case_dir).unwrap();

    assert_case_summary(&manifest, &summary);
    assert!(summary.findings.is_empty());
}

#[test]
fn policy_truthful_workspace_stays_clean() {
    let case_dir = case_dir("benign", "policy-truthful-basic");
    let manifest = load_case(&case_dir);
    let summary = harness().scan_case(&case_dir).unwrap();

    assert_case_summary(&manifest, &summary);
    assert!(
        summary
            .findings
            .iter()
            .all(|finding| !matches!(finding.rule_code.as_str(), "SEC401" | "SEC402" | "SEC403"))
    );
}

#[test]
fn package_manifest_supply_chain_cases_stay_clean_when_safe() {
    for case_name in [
        "docker-compose-digest-pinned-image",
        "docker-compose-safe-runtime",
        "docker-compose-tagged-image-safe",
        "dockerfile-digest-pinned-base-image",
        "dockerfile-final-stage-nonroot-user",
        "dockerfile-safe-run",
        "dockerfile-tagged-base-image-safe",
        "package-manifest-pinned-dependency-safe",
        "package-manifest-registry-archive-safe",
        "package-manifest-registry-dependency-safe",
        "package-manifest-safe-lifecycle-script",
    ] {
        let case_dir = case_dir("benign", case_name);
        let manifest = load_case(&case_dir);
        let summary = harness().scan_case(&case_dir).unwrap();
        assert_case_summary(&manifest, &summary);
        assert!(summary.findings.is_empty());
    }
}
